name: package_tn93_1_0_2
categories:
  - Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 1.0.2 of tn93
owner: nml
remote_repository_url: https://github.com/phac-nml/galaxy_tools/tree/master/packages/package_tn93_1_0_2
type: tool_dependency_definition
