language: python
python: 2.7
install:
  - pip install git+git://github.com/galaxyproject/planemo.git@master
  - mkdir `pwd`/cache ; mkdir `pwd`/install ;export DOWNLOAD_CACHE=`pwd`/cache; export INSTALL_DIR=`pwd`/install;planemo  dependency_script -r
script:
  - planemo shed_lint --report_level warn --tools --fail_level error --recursive .
  - bash dep_install.sh && source env.sh && planemo test tools/spades/
