name: package_python_3_4_fakemp_0_9_1
categories:
  - Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 0.9.1 of fakemp
owner: nml
remote_repository_url: https://github.com/phac-nml/galaxy_tools/tree/master/packages/package_python_3_4_fakemp_0_9_1
type: tool_dependency_definition
