categories: [Sequence Analysis]
description: An application that identifies potential transmission clusters within a supplied FASTA file with an option to find potential links against the Los Alamos HIV Sequence Database.
name: hivtrace
owner: nml
