name: package_python_3_4_six_1_10_0
categories:
  - Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 1.10.0 of six
owner: nml
remote_repository_url: https://github.com/phac-nml/galaxy_tools/tree/master/packages/package_python_3_4_six_1_10_0
type: tool_dependency_definition
