name: package_python_3_4_biopython_1_66
categories:
  - Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 1.66 of biopython
owner: nml
remote_repository_url: https://github.com/phac-nml/galaxy_tools/tree/master/packages/package_python_3_4_biopython_1_66
type: tool_dependency_definition
