name: package_python_3_4_scipy_0_16
categories:
  - Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 0.16 of scipy
owner: nml
remote_repository_url: https://github.com/phac-nml/galaxy_tools/tree/master/packages/package_python_3_4_scipy_0_16
type: tool_dependency_definition
