name: package_python_3_4_hyphy_python_0_1_3
categories:
  - Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 0.1.3 of hyphy-python
owner: nml
remote_repository_url: https://github.com/phac-nml/galaxy_tools/tree/master/packages/package_python_3_4_hyphy_python_0_1_3
type: tool_dependency_definition
