name: package_python_3_4_hyphy_2_2_6
categories:
  - Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 2.2.6 of hyphy
owner: nml
remote_repository_url: https://github.com/phac-nml/galaxy_tools/tree/master/packages/package_python_3_4_hyphy_2_2_6
type: tool_dependency_definition
